version: '3.8'
services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: "./"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: sh -c "/wait && npm run start"
    environment:
      WAIT_HOSTS: postgres:5432
    volumes:
      - ./:/usr/src/app/

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phone_book
    ports:
      - "5432:5432"
    volumes:
      - ./server/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: "./client"
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app/client
